version: '3'
services:
  db-crud:
    container_name: db-final-proyect-products
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: db-final-proyect-products
      POSTGRES_USER: java
      POSTGRES_PASSWORD: java
    ports:
      - 5431:5431
    expose:
      - 5431
    command:
      -p 5431